name: 'Test'
on:
  push:

jobs:
  build:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        percentile: [80.1, 95, 99.9]

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
        
      - name: 'Module install'
        run: pip install -r requirements.txt
          
      - name: 'Run script'
        run: python script.py ${{ matrix.percentile }}


